// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvgzcbrbwhhlfroakbdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Z3pjYnJid2hobGZyb2FrYmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzczMTksImV4cCI6MjA2ODE1MzMxOX0.cZQVv84Gov0OyJqo3jEBsfZdvBGXSgUv_iof_H4-kzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});